esphome:
  name: flora_gw
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: "Jifi IoT"
  password: !secret wifi_password

  ap:
    ssid: "Flora Gateway Fallback Hotspot"

captive_portal:

logger:

api:

ota:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
# sensor:
#   - platform: xiaomi_hhccjcy01
#     mac_address: 'C4:7C:8D:6B:48:63'
#     temperature:
#       name: "Xiaomi HHCCJCY01 :48:63 Temperature"
#     moisture:
#       name: "Xiaomi HHCCJCY01 :48:63 Moisture"
#     illuminance:
#       name: "Xiaomi HHCCJCY01 :48:63 Illuminance"
#     conductivity:
#       name: "Xiaomi HHCCJCY01 :48:63 Soil Conductivity"
#   - platform: xiaomi_hhccjcy01
#     mac_address: 'C4:7C:8D:6B:48:A6'
#     temperature:
#       name: "Xiaomi HHCCJCY01 :48:A6 Temperature"
#     moisture:
#       name: "Xiaomi HHCCJCY01 :48:A6 Moisture"
#     illuminance:
#       name: "Xiaomi HHCCJCY01 :48:A6 Illuminance"
#     conductivity:
#       name: "Xiaomi HHCCJCY01 :48:A6 Soil Conductivity"
