esphome:
  name: flora_gw
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: "Jifi IoT"
  password: !secret wifi_password

  ap:
    ssid: "Flora Gateway Fallback Hotspot"

captive_portal:

logger:

api:

ota:

esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

button:
  - platform: restart
    name: "Restart"
