esphome:
  name: heatmonitoring

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatmonitoring Fallback Hotspot"

captive_portal:

# Example configuration entry
dallas:
  - pin: 18
    update_interval: 30s

# Individual sensors
sensor:
  - platform: dallas
    address: 0x2b3ce1e381910928
    name: "0x2b3ce1e381910928"
  - platform: dallas
    address: 0x6a3ce1e381435f28
    name: "0x6a3ce1e381435f28"
  - platform: dallas
    address: 0xf63ce1e381c57328
    name: "0xf63ce1e381c57328"
  - platform: dallas
    address: 0x1b3ce1e38148da28
    name: "0x1b3ce1e38148da28"
  - platform: dallas
    address: 0x483ce1e381427c28
    name: "0x483ce1e381427c28"
  - platform: dallas
    address: 0x593ce1e381261828
    name: "0x593ce1e381261828"
  - platform: dallas
    address: 0x163ce1e38185ba28
    name: "0x163ce1e38185ba28"
  - platform: dallas
    address: 0x5c3ce1e381f05e28
    name: "0x5c3ce1e381f05e28"
  - platform: dallas
    address: 0xe63ce1e3812e3928
    name: "0xe63ce1e3812e3928"
  - platform: dallas
    address: 0x633ce1e3813eb728
    name: "0x633ce1e3813eb728"

  - platform: dallas
    address: 0x0a27cc9d1e64ff28
    name: "0x0a27cc9d1e64ff28"
  - platform: dallas
    address: 0x7db44c9c1e64ff28
    name: "0x7db44c9c1e64ff28"
  - platform: dallas
    address: 0x57a74f9c1e64ff28
    name: "0x57a74f9c1e64ff28"
  - platform: dallas
    address: 0x4213599c1e64ff28
    name: "0x4213599c1e64ff28"

  - platform: dallas
    address: 0x22104e9c1e64ff28
    name: "0x22104e9c1e64ff28"
  - platform: dallas
    address: 0xf4d66e9c1e64ff28
    name: "0xf4d66e9c1e64ff28"
  - platform: dallas
    address: 0xa2435d9c1e64ff28
    name: "0xa2435d9c1e64ff28"
  - platform: dallas
    address: 0xc9605b9c1e64ff28
    name: "0xc9605b9c1e64ff28"
  - platform: dallas
    address: 0x4ab0f99d1e64ff28
    name: "0x4ab0f99d1e64ff28"
  - platform: dallas
    address: 0xea55f19d1e64ff28
    name: "0xea55f19d1e64ff28"
