esphome:
  name: jonas_bed
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Jifi"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jonas Bed Fallback Hotspot"
    password: "F330kLxAMfag"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR Sensor 1"
    device_class: motion
  - platform: gpio
    pin: D6
    name: "PIR Sensor 2"
    device_class: motion

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 3
    rgb_order: GRB
    name: "LED 1"
    effects:
      - strobe:
      - random:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D5
    num_leds: 3
    rgb_order: GRB
    name: "LED 2"
    effects:
      - strobe:
      - random:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
