esphome:
  name: lampis
  friendly_name: Lampis

esp8266:
  board: d1_mini_pro
  framework:
    version: 2.7.4

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  # https://esphome.io/components/light/index.html
  - name: "Lampis"
    num_leds: 144

    platform: fastled_spi
    chipset: APA102
    data_pin: D7
    clock_pin: D5

    effects:
      - random:
      # - wled:
      - addressable_rainbow:
          speed: 5
          width: 144
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - addressable_lambda:
          name: "Saftis"
          update_interval: 16ms
          lambda: |-
            static uint16_t width = 14;
            static uint16_t pos = 0;

            it.all() = Color::BLACK;

            uint16_t end_pos = pos + width;
            if (end_pos > 144) {
              uint16_t overflow = end_pos - 144;
              it.range(0, overflow) = current_color;
              end_pos = 144;
            }

            it.range(pos, end_pos) = current_color;

            pos = (pos + 1) % 144;



# Example configuration entry
dallas:
  - pin: GPIO5

sensor:
  - platform: dallas
    address: 0x800417039D6EFF28
    name: "Tempis"

